### ISSUE TITLE
okp4 rebrand

### ISSUE THREAD

**Issue by reversesigh** [polkachu/cosmos-port-prefixes#35]
Okp4 has rebranded as axone. Should the entry ` "okp4": 176,` be updated to reflect this?

**Comment by PolkachuIntern** [comment]
Yes, sounds about right. You update it or I do it?

**Comment by PolkachuIntern** [comment]
done https://github.com/polkachu/cosmos-port-prefixes/commit/b9b158b26c8da97beb4662876de324b67d597c7e
